apiVersion: pingcap.com/v1alpha1
kind: TidbNGMonitoring
metadata:
  name: ngmonitor
  namespace: sit-tidb
spec:
  clusters:
  - name: rnp-tidb
    namespace: sit-tidb
  pvReclaimPolicy: Retain
  ngMonitoring:
    requests:
      storage: 10Gi
    version: v6.1.0
    storageClassName: "default"
    baseImage: pingcap/ng-monitoring
  nodeSelector:
    nodepool: monitor
