apiVersion: pingcap.com/v1alpha1
kind: TidbNGMonitoring
metadata:
  name: ngmonitoring
  namespace: sit-tidb
spec:
  clusters:
  - name: rnp-tidb
    namespace: sit-tidb
  pvReclaimPolicy: Retain
  ngMonitoring:
    requests:
      storage: 10Gi
    version: v6.1.0
    storageClassName: "csi-disk-sit-rnp-ngmonitor"
    baseImage: pingcap/ng-monitoring
    nodeSelector:
      nodepool: monitor

