apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-tikv1
spec:
  storageClassName: sc-ssd-storage
  capacity:
    storage: 500Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
