kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-disk-sit-rnp-db
provisioner: everest-csi-provisioner
parameters:
  csi.storage.k8s.io/csi-driver-name: disk.csi.everest.io
  csi.storage.k8s.io/fstype: ext4
  everest.io/disk-volume-type: SSD
  everest.io/passthrough: 'true'
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
