apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: sit-tidb
  name: sc-ssd-storage
provisioner: cluster.local/nfs-subdir-external-provisioner
parameters:
  server: 10.57.48.86
  path: /
  readOnly: "false"
allowVolumeExpansion: true
